"""
Catalogo base CNAE para autocompletado en formularios.
Clave: codigo CNAE (string numerica), Valor: descripcion.
"""

CNAE_CATALOG = {
    "0111": "Cultivo de cereales (excepto arroz), leguminosas y semillas oleaginosas",
    "0113": "Cultivo de hortalizas, raices y tuberculos",
    "0123": "Cultivo de citricos",
    "0146": "Explotacion de ganado porcino",
    "0161": "Actividades de apoyo a la agricultura",
    "0311": "Pesca marina",
    "1011": "Procesado y conservacion de carne",
    "1043": "Fabricacion de aceite de oliva",
    "1071": "Fabricacion de pan y de productos frescos de panaderia y pasteleria",
    "1102": "Elaboracion de vinos",
    "1413": "Confeccion de otras prendas de vestir exteriores",
    "1419": "Confeccion de otras prendas de vestir y accesorios",
    "1812": "Otras actividades de impresion y artes graficas",
    "2222": "Fabricacion de envases y embalajes de plastico",
    "2511": "Fabricacion de estructuras metalicas y sus componentes",
    "2562": "Ingenieria mecanica por cuenta de terceros",
    "2573": "Fabricacion de herramientas",
    "2599": "Fabricacion de otros productos metalicos n.c.o.p.",
    "2620": "Fabricacion de ordenadores y equipos perifericos",
    "2711": "Fabricacion de motores, generadores y transformadores electricos",
    "2899": "Fabricacion de otra maquinaria para usos especificos n.c.o.p.",
    "3109": "Fabricacion de otros muebles",
    "3299": "Otras industrias manufactureras n.c.o.p.",
    "3312": "Reparacion de maquinaria",
    "3519": "Produccion de energia electrica de otros tipos",
    "3600": "Captacion, depuracion y distribucion de agua",
    "3811": "Recogida de residuos no peligrosos",
    "4110": "Promocion inmobiliaria",
    "4121": "Construccion de edificios residenciales",
    "4122": "Construccion de edificios no residenciales",
    "4211": "Construccion de carreteras y autopistas",
    "4221": "Construccion de redes para fluidos",
    "4299": "Construccion de otros proyectos de ingenieria civil n.c.o.p.",
    "4311": "Demolicion",
    "4312": "Preparacion de terrenos",
    "4321": "Instalaciones electricas",
    "4322": "Fontaneria, instalaciones de sistemas de calefaccion y aire acondicionado",
    "4329": "Otras instalaciones en obras de construccion",
    "4332": "Instalacion de carpinteria",
    "4334": "Pintura y acristalamiento",
    "4399": "Otras actividades de construccion especializada n.c.o.p.",
    "4511": "Venta de automoviles y vehiculos de motor ligeros",
    "4519": "Venta de otros vehiculos de motor",
    "4520": "Mantenimiento y reparacion de vehiculos de motor",
    "4531": "Comercio al por mayor de repuestos y accesorios de vehiculos de motor",
    "4540": "Venta, mantenimiento y reparacion de motocicletas y de sus repuestos y accesorios",
    "4611": "Intermediarios del comercio de materias primas agrarias, animales vivos, materias primas textiles y productos semielaborados",
    "4619": "Intermediarios del comercio de productos diversos",
    "4621": "Comercio al por mayor de cereales, tabaco en rama, simientes y alimentos para animales",
    "4631": "Comercio al por mayor de frutas y hortalizas",
    "4632": "Comercio al por mayor de carne y productos carnicos",
    "4634": "Comercio al por mayor de bebidas",
    "4638": "Comercio al por mayor de pescados, mariscos y otros productos alimenticios",
    "4643": "Comercio al por mayor de aparatos electrodomesticos",
    "4649": "Comercio al por mayor de otros articulos de uso domestico",
    "4651": "Comercio al por mayor de ordenadores, equipos perifericos y programas informaticos",
    "4652": "Comercio al por mayor de equipos electronicos y de telecomunicaciones y sus componentes",
    "4661": "Comercio al por mayor de maquinaria, equipos y suministros agricolas",
    "4662": "Comercio al por mayor de maquinas herramienta",
    "4663": "Comercio al por mayor de maquinaria para la mineria, la construccion y la ingenieria civil",
    "4665": "Comercio al por mayor de muebles de oficina",
    "4666": "Comercio al por mayor de otra maquinaria y equipo de oficina",
    "4669": "Comercio al por mayor de otra maquinaria y equipo",
    "4671": "Comercio al por mayor de combustibles solidos, liquidos y gaseosos, y productos similares",
    "4672": "Comercio al por mayor de metales y minerales metalicos",
    "4673": "Comercio al por mayor de madera, materiales de construccion y aparatos sanitarios",
    "4690": "Comercio al por mayor no especializado",
    "4711": "Comercio al por menor en establecimientos no especializados, con predominio en productos alimenticios, bebidas y tabaco",
    "4719": "Otro comercio al por menor en establecimientos no especializados",
    "4721": "Comercio al por menor de frutas y hortalizas en establecimientos especializados",
    "4724": "Comercio al por menor de pan y productos de panaderia, confiteria y pasteleria en establecimientos especializados",
    "4730": "Comercio al por menor de combustible para la automocion en establecimientos especializados",
    "4741": "Comercio al por menor de ordenadores, equipos perifericos y programas informaticos en establecimientos especializados",
    "4751": "Comercio al por menor de textiles en establecimientos especializados",
    "4752": "Comercio al por menor de ferreteria, pintura y vidrio en establecimientos especializados",
    "4754": "Comercio al por menor de aparatos electrodomesticos en establecimientos especializados",
    "4759": "Comercio al por menor de muebles, aparatos de iluminacion y otros articulos de uso domestico en establecimientos especializados",
    "4761": "Comercio al por menor de libros en establecimientos especializados",
    "4771": "Comercio al por menor de prendas de vestir en establecimientos especializados",
    "4773": "Comercio al por menor de productos farmaceuticos en establecimientos especializados",
    "4778": "Otro comercio al por menor de articulos nuevos en establecimientos especializados",
    "4779": "Comercio al por menor de articulos de segunda mano en establecimientos",
    "4781": "Comercio al por menor de productos alimenticios, bebidas y tabaco en puestos de venta y mercadillos",
    "4791": "Comercio al por menor por correspondencia o Internet",
    "4931": "Transporte terrestre urbano y suburbano de pasajeros",
    "4932": "Transporte por taxi",
    "4941": "Transporte de mercancias por carretera",
    "5210": "Deposito y almacenamiento",
    "5221": "Actividades anexas al transporte terrestre",
    "5310": "Actividades postales sometidas a la obligacion del servicio universal",
    "5510": "Hoteles y alojamientos similares",
    "5520": "Alojamientos turisticos y otros alojamientos de corta estancia",
    "5610": "Restaurantes y puestos de comidas",
    "5621": "Provision de comidas preparadas para eventos",
    "5630": "Establecimientos de bebidas",
    "5811": "Edicion de libros",
    "5813": "Edicion de periodicos",
    "5821": "Edicion de videojuegos",
    "5829": "Edicion de otros programas informaticos",
    "6110": "Telecomunicaciones por cable",
    "6120": "Telecomunicaciones inalambricas",
    "6190": "Otras actividades de telecomunicaciones",
    "6201": "Actividades de programacion informatica",
    "6202": "Actividades de consultoria informatica",
    "6209": "Otros servicios relacionados con las tecnologias de la informacion y la informatica",
    "6311": "Proceso de datos, hosting y actividades relacionadas",
    "6399": "Otros servicios de informacion n.c.o.p.",
    "6419": "Otra intermediacion monetaria",
    "6420": "Actividades de las sociedades holding",
    "6499": "Otros servicios financieros, excepto seguros y fondos de pensiones n.c.o.p.",
    "6622": "Actividades de agentes y corredores de seguros",
    "6810": "Compraventa de bienes inmobiliarios por cuenta propia",
    "6820": "Alquiler de bienes inmobiliarios por cuenta propia",
    "6831": "Agentes de la propiedad inmobiliaria",
    "6832": "Gestion y administracion de la propiedad inmobiliaria",
    "6910": "Actividades juridicas",
    "6920": "Actividades de contabilidad, teneduria de libros, auditoria y asesoria fiscal",
    "7010": "Actividades de las sedes centrales",
    "7022": "Otras actividades de consultoria de gestion empresarial",
    "7111": "Servicios tecnicos de arquitectura",
    "7112": "Servicios tecnicos de ingenieria y otras actividades relacionadas con el asesoramiento tecnico",
    "7120": "Ensayos y analisis tecnicos",
    "7219": "Otra investigacion y desarrollo experimental en ciencias naturales y tecnicas",
    "7311": "Agencias de publicidad",
    "7312": "Servicios de representacion de medios de comunicacion",
    "7410": "Actividades de diseño especializado",
    "7420": "Actividades de fotografia",
    "7430": "Actividades de traduccion e interpretacion",
    "7490": "Otras actividades profesionales, cientificas y tecnicas n.c.o.p.",
    "7500": "Actividades veterinarias",
    "7711": "Alquiler de automoviles y vehiculos de motor ligeros",
    "7732": "Alquiler de maquinaria y equipo para la construccion e ingenieria civil",
    "7810": "Actividades de las agencias de colocacion",
    "7820": "Actividades de las empresas de trabajo temporal",
    "7830": "Otra provision de recursos humanos",
    "7911": "Actividades de las agencias de viajes",
    "8110": "Servicios integrales a edificios e instalaciones",
    "8121": "Limpieza general de edificios",
    "8130": "Actividades de jardineria",
    "8211": "Servicios administrativos combinados",
    "8219": "Actividades de fotocopiado, preparacion de documentos y otras actividades especializadas de oficina",
    "8299": "Otras actividades de apoyo a las empresas n.c.o.p.",
    "8559": "Otra educacion n.c.o.p.",
    "8621": "Actividades de medicina general",
    "8622": "Actividades de medicina especializada",
    "8690": "Otras actividades sanitarias",
    "8811": "Actividades de servicios sociales sin alojamiento para personas mayores",
    "9001": "Artes escenicas",
    "9311": "Gestion de instalaciones deportivas",
    "9313": "Actividades de los gimnasios",
    "9329": "Otras actividades recreativas y de entretenimiento",
    "9499": "Otras actividades asociativas n.c.o.p.",
    "9602": "Peluqueria y otros tratamientos de belleza",
    "9609": "Otros servicios personales n.c.o.p.",
}
